---
name: Build
on:
  push:
    branches:
      - master
      - renovate/**
    paths-ignore:
      - "**.md"
      - LICENSE
      - renovate.json
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - LICENSE
      - renovate.json

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup JDK
        uses: actions/setup-java@v3.3.0
        with:
          distribution: temurin
          java-version: "17"
      - uses: actions/cache@v3.0.4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: mvn clean
        run: ./mvnw -Dstyle.color=always clean
      - name: mvn package
        run: ./mvnw -Dstyle.color=always -Dspring.output.ansi.enabled=ALWAYS package
